// <auto-generated />
namespace aspMVCDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddAuditing_To_Account_Entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAuditing_To_Account_Entity));
        
        string IMigrationMetadata.Id
        {
            get { return "202110151052536_AddAuditing_To_Account_Entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
